In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [2]:
import os
from dotenv import load_dotenv

load_dotenv()

True

In [3]:
from datetime import date
from common import Operator

# Use one of 'blekinge', 'dintur', 'dt', 'gotland', 'halland', 'klt', 'krono', 'orebro', 'otraf', 'sj', 'skane', 'sl', 'sormland', 'ul', 'varm', 'vastmanland', 'vt', 'xt'
operator = Operator.SL
year = 2024
month = 6
day = 15
hour = 10
myDate = date(year, month, day)
feedId = "TripUpdates"

In [4]:
from koda import download_koda_rt_file, download_koda_static_file

KODA_API_KEY = os.getenv("KODA_API_KEY")
if not KODA_API_KEY:
    raise ValueError("KODA_API_KEY not found in environment variables")

download_koda_rt_file(operator, feedId, myDate, hour, api_key=KODA_API_KEY, data_dir="../data/koda-rt")

download_koda_static_file(operator, myDate, api_key=KODA_API_KEY, data_dir="../data/koda-static")

File ../data/koda-rt/sl_2024-06-15.7z already exists. Skipping download.
File ../data/koda-static/sl_2024-06-15.zip already exists. Skipping download.

In [5]:
from gtfs import  load_pb_file

data_folder = f"../data/koda-rt/data-tmp/sl/{feedId}/{year}/{month:02d}/{day:02d}/{hour:02d}"

files_in_data_folder = os.listdir(data_folder)
print("Files in data folder:", files_in_data_folder)

first_file_path = os.path.join(data_folder, files_in_data_folder[0])

gtfs_data = load_pb_file(first_file_path)

Files in data folder: ['sl-tripupdates-2024-06-15T10-00-03Z.pb', 'sl-tripupdates-2024-06-15T10-00-17Z.pb', 'sl-tripupdates-2024-06-15T10-00-31Z.pb', 'sl-tripupdates-2024-06-15T10-00-45Z.pb', 'sl-tripupdates-2024-06-15T10-01-13Z.pb', 'sl-tripupdates-2024-06-15T10-01-27Z.pb', 'sl-tripupdates-2024-06-15T10-01-41Z.pb', 'sl-tripupdates-2024-06-15T10-01-55Z.pb', 'sl-tripupdates-2024-06-15T10-02-09Z.pb', 'sl-tripupdates-2024-06-15T10-02-23Z.pb', 'sl-tripupdates-2024-06-15T10-02-37Z.pb', 'sl-tripupdates-2024-06-15T10-02-51Z.pb', 'sl-tripupdates-2024-06-15T10-03-05Z.pb', 'sl-tripupdates-2024-06-15T10-03-19Z.pb', 'sl-tripupdates-2024-06-15T10-03-33Z.pb', 'sl-tripupdates-2024-06-15T10-03-47Z.pb', 'sl-tripupdates-2024-06-15T10-04-01Z.pb', 'sl-tripupdates-2024-06-15T10-04-15Z.pb', 'sl-tripupdates-2024-06-15T10-04-29Z.pb', 'sl-tripupdates-2024-06-15T10-04-43Z.pb', 'sl-tripupdates-2024-06-15T10-05-11Z.pb', 'sl-tripupdates-2024-06-15T10-05-25Z.pb', 'sl-tripupdates-2024-06-15T10-05-39Z.pb', 'sl-tripupdates-2024-06-15T10-05-53Z.pb', 'sl-tripupdates-2024-06-15T10-06-07Z.pb', 'sl-tripupdates-2024-06-15T10-06-21Z.pb', 'sl-tripupdates-2024-06-15T10-06-35Z.pb', 'sl-tripupdates-2024-06-15T10-06-49Z.pb', 'sl-tripupdates-2024-06-15T10-07-03Z.pb', 'sl-tripupdates-2024-06-15T10-07-17Z.pb', 'sl-tripupdates-2024-06-15T10-07-31Z.pb', 'sl-tripupdates-2024-06-15T10-07-45Z.pb', 'sl-tripupdates-2024-06-15T10-08-13Z.pb', 'sl-tripupdates-2024-06-15T10-08-27Z.pb', 'sl-tripupdates-2024-06-15T10-08-41Z.pb', 'sl-tripupdates-2024-06-15T10-08-55Z.pb', 'sl-tripupdates-2024-06-15T10-09-09Z.pb', 'sl-tripupdates-2024-06-15T10-09-23Z.pb', 'sl-tripupdates-2024-06-15T10-09-37Z.pb', 'sl-tripupdates-2024-06-15T10-09-51Z.pb', 'sl-tripupdates-2024-06-15T10-10-05Z.pb', 'sl-tripupdates-2024-06-15T10-10-19Z.pb', 'sl-tripupdates-2024-06-15T10-10-33Z.pb', 'sl-tripupdates-2024-06-15T10-10-47Z.pb', 'sl-tripupdates-2024-06-15T10-11-01Z.pb', 'sl-tripupdates-2024-06-15T10-11-15Z.pb', 'sl-tripupdates-2024-06-15T10-11-29Z.pb', 'sl-tripupdates-2024-06-15T10-11-43Z.pb', 'sl-tripupdates-2024-06-15T10-11-57Z.pb', 'sl-tripupdates-2024-06-15T10-12-11Z.pb', 'sl-tripupdates-2024-06-15T10-12-25Z.pb', 'sl-tripupdates-2024-06-15T10-12-39Z.pb', 'sl-tripupdates-2024-06-15T10-12-53Z.pb', 'sl-tripupdates-2024-06-15T10-13-07Z.pb', 'sl-tripupdates-2024-06-15T10-13-21Z.pb', 'sl-tripupdates-2024-06-15T10-13-35Z.pb', 'sl-tripupdates-2024-06-15T10-13-49Z.pb', 'sl-tripupdates-2024-06-15T10-14-03Z.pb', 'sl-tripupdates-2024-06-15T10-14-17Z.pb', 'sl-tripupdates-2024-06-15T10-14-31Z.pb', 'sl-tripupdates-2024-06-15T10-14-45Z.pb', 'sl-tripupdates-2024-06-15T10-14-59Z.pb', 'sl-tripupdates-2024-06-15T10-15-13Z.pb', 'sl-tripupdates-2024-06-15T10-15-27Z.pb', 'sl-tripupdates-2024-06-15T10-15-41Z.pb', 'sl-tripupdates-2024-06-15T10-15-55Z.pb', 'sl-tripupdates-2024-06-15T10-16-09Z.pb', 'sl-tripupdates-2024-06-15T10-16-23Z.pb', 'sl-tripupdates-2024-06-15T10-16-37Z.pb', 'sl-tripupdates-2024-06-15T10-16-51Z.pb', 'sl-tripupdates-2024-06-15T10-17-05Z.pb', 'sl-tripupdates-2024-06-15T10-17-19Z.pb', 'sl-tripupdates-2024-06-15T10-17-33Z.pb', 'sl-tripupdates-2024-06-15T10-17-47Z.pb', 'sl-tripupdates-2024-06-15T10-18-01Z.pb', 'sl-tripupdates-2024-06-15T10-18-15Z.pb', 'sl-tripupdates-2024-06-15T10-18-29Z.pb', 'sl-tripupdates-2024-06-15T10-18-43Z.pb', 'sl-tripupdates-2024-06-15T10-18-57Z.pb', 'sl-tripupdates-2024-06-15T10-19-11Z.pb', 'sl-tripupdates-2024-06-15T10-19-25Z.pb', 'sl-tripupdates-2024-06-15T10-19-39Z.pb', 'sl-tripupdates-2024-06-15T10-19-53Z.pb', 'sl-tripupdates-2024-06-15T10-20-07Z.pb', 'sl-tripupdates-2024-06-15T10-20-21Z.pb', 'sl-tripupdates-2024-06-15T10-20-35Z.pb', 'sl-tripupdates-2024-06-15T10-20-49Z.pb', 'sl-tripupdates-2024-06-15T10-21-03Z.pb', 'sl-tripupdates-2024-06-15T10-21-17Z.pb', 'sl-tripupdates-2024-06-15T10-21-31Z.pb', 'sl-tripupdates-2024-06-15T10-21-45Z.pb', 'sl-tripupdates-2024-06-15T10-21-59Z.pb', 'sl-tripupdates-2024-06-15T10-22-13Z.pb', 'sl-tripupdates-2024-06-15T10-22-27Z.pb', 'sl-tripupdates-2024-06-15T10-22-41Z.pb', 'sl-tripupdates-2024-06-15T10-22-55Z.pb', 'sl-tripupdates-2024-06-15T10-23-09Z.pb', 'sl-tripupdates-2024-06-15T10-23-23Z.pb', 'sl-tripupdates-2024-06-15T10-23-37Z.pb', 'sl-tripupdates-2024-06-15T10-23-51Z.pb', 'sl-tripupdates-2024-06-15T10-24-05Z.pb', 'sl-tripupdates-2024-06-15T10-24-19Z.pb', 'sl-tripupdates-2024-06-15T10-24-33Z.pb', 'sl-tripupdates-2024-06-15T10-24-47Z.pb', 'sl-tripupdates-2024-06-15T10-25-01Z.pb', 'sl-tripupdates-2024-06-15T10-25-15Z.pb', 'sl-tripupdates-2024-06-15T10-25-29Z.pb', 'sl-tripupdates-2024-06-15T10-25-43Z.pb', 'sl-tripupdates-2024-06-15T10-26-11Z.pb', 'sl-tripupdates-2024-06-15T10-26-25Z.pb', 'sl-tripupdates-2024-06-15T10-26-39Z.pb', 'sl-tripupdates-2024-06-15T10-26-53Z.pb', 'sl-tripupdates-2024-06-15T10-27-07Z.pb', 'sl-tripupdates-2024-06-15T10-27-21Z.pb', 'sl-tripupdates-2024-06-15T10-27-35Z.pb', 'sl-tripupdates-2024-06-15T10-27-49Z.pb', 'sl-tripupdates-2024-06-15T10-28-03Z.pb', 'sl-tripupdates-2024-06-15T10-28-17Z.pb', 'sl-tripupdates-2024-06-15T10-28-31Z.pb', 'sl-tripupdates-2024-06-15T10-28-45Z.pb', 'sl-tripupdates-2024-06-15T10-28-59Z.pb', 'sl-tripupdates-2024-06-15T10-29-13Z.pb', 'sl-tripupdates-2024-06-15T10-29-27Z.pb', 'sl-tripupdates-2024-06-15T10-29-41Z.pb', 'sl-tripupdates-2024-06-15T10-29-55Z.pb', 'sl-tripupdates-2024-06-15T10-30-09Z.pb', 'sl-tripupdates-2024-06-15T10-30-23Z.pb', 'sl-tripupdates-2024-06-15T10-30-37Z.pb', 'sl-tripupdates-2024-06-15T10-30-51Z.pb', 'sl-tripupdates-2024-06-15T10-31-05Z.pb', 'sl-tripupdates-2024-06-15T10-31-19Z.pb', 'sl-tripupdates-2024-06-15T10-31-33Z.pb', 'sl-tripupdates-2024-06-15T10-31-47Z.pb', 'sl-tripupdates-2024-06-15T10-32-01Z.pb', 'sl-tripupdates-2024-06-15T10-32-15Z.pb', 'sl-tripupdates-2024-06-15T10-32-29Z.pb', 'sl-tripupdates-2024-06-15T10-32-43Z.pb', 'sl-tripupdates-2024-06-15T10-32-57Z.pb', 'sl-tripupdates-2024-06-15T10-33-11Z.pb', 'sl-tripupdates-2024-06-15T10-33-25Z.pb', 'sl-tripupdates-2024-06-15T10-33-39Z.pb', 'sl-tripupdates-2024-06-15T10-33-53Z.pb', 'sl-tripupdates-2024-06-15T10-34-07Z.pb', 'sl-tripupdates-2024-06-15T10-34-21Z.pb', 'sl-tripupdates-2024-06-15T10-34-35Z.pb', 'sl-tripupdates-2024-06-15T10-34-49Z.pb', 'sl-tripupdates-2024-06-15T10-35-03Z.pb', 'sl-tripupdates-2024-06-15T10-35-17Z.pb', 'sl-tripupdates-2024-06-15T10-35-31Z.pb', 'sl-tripupdates-2024-06-15T10-35-45Z.pb', 'sl-tripupdates-2024-06-15T10-35-59Z.pb', 'sl-tripupdates-2024-06-15T10-36-13Z.pb', 'sl-tripupdates-2024-06-15T10-36-27Z.pb', 'sl-tripupdates-2024-06-15T10-36-41Z.pb', 'sl-tripupdates-2024-06-15T10-36-55Z.pb', 'sl-tripupdates-2024-06-15T10-37-09Z.pb', 'sl-tripupdates-2024-06-15T10-37-23Z.pb', 'sl-tripupdates-2024-06-15T10-37-37Z.pb', 'sl-tripupdates-2024-06-15T10-37-51Z.pb', 'sl-tripupdates-2024-06-15T10-38-05Z.pb', 'sl-tripupdates-2024-06-15T10-38-19Z.pb', 'sl-tripupdates-2024-06-15T10-38-33Z.pb', 'sl-tripupdates-2024-06-15T10-38-47Z.pb', 'sl-tripupdates-2024-06-15T10-39-01Z.pb', 'sl-tripupdates-2024-06-15T10-39-15Z.pb', 'sl-tripupdates-2024-06-15T10-39-29Z.pb', 'sl-tripupdates-2024-06-15T10-39-43Z.pb', 'sl-tripupdates-2024-06-15T10-39-57Z.pb', 'sl-tripupdates-2024-06-15T10-40-11Z.pb', 'sl-tripupdates-2024-06-15T10-40-25Z.pb', 'sl-tripupdates-2024-06-15T10-40-39Z.pb', 'sl-tripupdates-2024-06-15T10-40-53Z.pb', 'sl-tripupdates-2024-06-15T10-41-07Z.pb', 'sl-tripupdates-2024-06-15T10-41-21Z.pb', 'sl-tripupdates-2024-06-15T10-41-35Z.pb', 'sl-tripupdates-2024-06-15T10-41-49Z.pb', 'sl-tripupdates-2024-06-15T10-42-03Z.pb', 'sl-tripupdates-2024-06-15T10-42-17Z.pb', 'sl-tripupdates-2024-06-15T10-42-31Z.pb', 'sl-tripupdates-2024-06-15T10-42-45Z.pb', 'sl-tripupdates-2024-06-15T10-42-59Z.pb', 'sl-tripupdates-2024-06-15T10-43-13Z.pb', 'sl-tripupdates-2024-06-15T10-43-27Z.pb', 'sl-tripupdates-2024-06-15T10-43-41Z.pb', 'sl-tripupdates-2024-06-15T10-43-55Z.pb', 'sl-tripupdates-2024-06-15T10-44-09Z.pb', 'sl-tripupdates-2024-06-15T10-44-23Z.pb', 'sl-tripupdates-2024-06-15T10-44-37Z.pb', 'sl-tripupdates-2024-06-15T10-44-51Z.pb', 'sl-tripupdates-2024-06-15T10-45-05Z.pb', 'sl-tripupdates-2024-06-15T10-45-19Z.pb', 'sl-tripupdates-2024-06-15T10-45-33Z.pb', 'sl-tripupdates-2024-06-15T10-45-47Z.pb', 'sl-tripupdates-2024-06-15T10-46-01Z.pb', 'sl-tripupdates-2024-06-15T10-46-15Z.pb', 'sl-tripupdates-2024-06-15T10-46-29Z.pb', 'sl-tripupdates-2024-06-15T10-46-43Z.pb', 'sl-tripupdates-2024-06-15T10-46-57Z.pb', 'sl-tripupdates-2024-06-15T10-47-11Z.pb', 'sl-tripupdates-2024-06-15T10-47-25Z.pb', 'sl-tripupdates-2024-06-15T10-47-39Z.pb', 'sl-tripupdates-2024-06-15T10-47-53Z.pb', 'sl-tripupdates-2024-06-15T10-48-07Z.pb', 'sl-tripupdates-2024-06-15T10-48-21Z.pb', 'sl-tripupdates-2024-06-15T10-48-35Z.pb', 'sl-tripupdates-2024-06-15T10-48-49Z.pb', 'sl-tripupdates-2024-06-15T10-49-03Z.pb', 'sl-tripupdates-2024-06-15T10-49-17Z.pb', 'sl-tripupdates-2024-06-15T10-49-31Z.pb', 'sl-tripupdates-2024-06-15T10-49-45Z.pb', 'sl-tripupdates-2024-06-15T10-50-13Z.pb', 'sl-tripupdates-2024-06-15T10-50-27Z.pb', 'sl-tripupdates-2024-06-15T10-50-41Z.pb', 'sl-tripupdates-2024-06-15T10-50-55Z.pb', 'sl-tripupdates-2024-06-15T10-51-09Z.pb', 'sl-tripupdates-2024-06-15T10-51-23Z.pb', 'sl-tripupdates-2024-06-15T10-51-37Z.pb', 'sl-tripupdates-2024-06-15T10-51-51Z.pb', 'sl-tripupdates-2024-06-15T10-52-05Z.pb', 'sl-tripupdates-2024-06-15T10-52-19Z.pb', 'sl-tripupdates-2024-06-15T10-52-33Z.pb', 'sl-tripupdates-2024-06-15T10-52-47Z.pb', 'sl-tripupdates-2024-06-15T10-53-01Z.pb', 'sl-tripupdates-2024-06-15T10-53-15Z.pb', 'sl-tripupdates-2024-06-15T10-53-29Z.pb', 'sl-tripupdates-2024-06-15T10-53-43Z.pb', 'sl-tripupdates-2024-06-15T10-54-11Z.pb', 'sl-tripupdates-2024-06-15T10-54-25Z.pb', 'sl-tripupdates-2024-06-15T10-54-39Z.pb', 'sl-tripupdates-2024-06-15T10-54-53Z.pb', 'sl-tripupdates-2024-06-15T10-55-07Z.pb', 'sl-tripupdates-2024-06-15T10-55-21Z.pb', 'sl-tripupdates-2024-06-15T10-55-35Z.pb', 'sl-tripupdates-2024-06-15T10-55-49Z.pb', 'sl-tripupdates-2024-06-15T10-56-03Z.pb', 'sl-tripupdates-2024-06-15T10-56-17Z.pb', 'sl-tripupdates-2024-06-15T10-56-31Z.pb', 'sl-tripupdates-2024-06-15T10-56-45Z.pb', 'sl-tripupdates-2024-06-15T10-56-59Z.pb', 'sl-tripupdates-2024-06-15T10-57-13Z.pb', 'sl-tripupdates-2024-06-15T10-57-27Z.pb', 'sl-tripupdates-2024-06-15T10-57-41Z.pb', 'sl-tripupdates-2024-06-15T10-57-55Z.pb', 'sl-tripupdates-2024-06-15T10-58-09Z.pb', 'sl-tripupdates-2024-06-15T10-58-23Z.pb', 'sl-tripupdates-2024-06-15T10-58-37Z.pb', 'sl-tripupdates-2024-06-15T10-58-51Z.pb', 'sl-tripupdates-2024-06-15T10-59-05Z.pb', 'sl-tripupdates-2024-06-15T10-59-19Z.pb', 'sl-tripupdates-2024-06-15T10-59-33Z.pb', 'sl-tripupdates-2024-06-15T10-59-47Z.pb']

In [6]:
from __generated__ import gtfs_realtime_pb2


def debug_print_feed(entity: gtfs_realtime_pb2.FeedEntity):
    id = entity.id
    trip_update = entity.trip_update
    trip = trip_update.trip
    stop_time_update = trip_update.stop_time_update

    # print("Trip update")
    # print(trip_update)
    # print("Trip")
    # print(trip)
    # print("Stop time updates")
    # print(stop_time_update)

    # print(f"Entity ID: {entity.id}")
    for (id, a) in entity.trip_update.ListFields():
        print(f"  Field: {id.name}")
        # print(f"    Value: {a}")
    


# print(f"Parsed FeedMessage with {len(gtfs_data.entity)} entities")
gtfs_entity = gtfs_data.entity[0]

debug_print_feed(gtfs_entity)

print("Total entities in feed:", len(gtfs_data.entity))

  Field: trip
  Field: stop_time_update
  Field: vehicle
  Field: timestamp
Total entities in feed: 689

In [7]:

def feed_trip_to_dict(entity: gtfs_realtime_pb2.FeedEntity) -> dict:
    return {
        "id": entity.id,
        "trip_id": entity.trip_update.trip.trip_id,
        "start_date": entity.trip_update.trip.start_date,
        "schedule_relationship": entity.trip_update.trip.schedule_relationship,
        "vehicle_id": entity.trip_update.vehicle.id,
        "stop_time_updates": [
            {
                "stop_sequence": stu.stop_sequence,
                "stop_id": stu.stop_id,
                "arrival_time": stu.arrival.time if stu.HasField("arrival") else None,
                "departure_time": stu.departure.time if stu.HasField("departure") else None,
                "schedule_relationship": stu.schedule_relationship,
            }
            for stu in entity.trip_update.stop_time_update
        ],
        "timestamp": gtfs_data.header.timestamp,
    }

feed_entities_dicts = [feed_trip_to_dict(e) for e in gtfs_data.entity]
df = pd.DataFrame(feed_entities_dicts)
df["id"] = df["id"].astype(pd.Int64Dtype())
df["trip_id"] = df["trip_id"].replace("", pd.NA).astype(pd.StringDtype())
df["vehicle_id"] = df["vehicle_id"].replace("", pd.NA).astype(pd.Int64Dtype())

print(df.dtypes)

df.head()

id                                Int64
trip_id                  string[python]
start_date                       object
schedule_relationship             int64
vehicle_id                        Int64
stop_time_updates                object
timestamp                         int64
dtype: object

,id,trip_id,start_date,schedule_relationship,vehicle_id,stop_time_updates,timestamp
0,14010516247726276,14010000663741929,20240615,0,9031008000500536,"[{'stop_sequence': 25, 'stop_id': '90220010001...",1718438398
1,14010516247729020,14010000663747674,20240615,0,9031008000500539,"[{'stop_sequence': 11, 'stop_id': '90220010001...",1718438398
2,14010516089523031,14010000656705623,20240615,0,9031001004002220,"[{'stop_sequence': 24, 'stop_id': '90220010050...",1718438398
3,14010516113220145,14010000656788822,20240615,0,9031001004302521,"[{'stop_sequence': 21, 'stop_id': '90220010061...",1718438398
4,14010516089526040,14010000656705875,20240615,0,9031001004002221,"[{'stop_sequence': 21, 'stop_id': '90220010051...",1718438398

In [8]:
trips = pd.read_csv("../data/koda-static/data-tmp/trips.txt", dtype={
  "trip_id": pd.StringDtype,
  "route_id": pd.StringDtype,
  "trip_headsign": pd.StringDtype,
  "service_id": "Int64",
  "shape_id": "Int64",
})

trips = trips.set_index("trip_id")

print(trips.dtypes)

trips.head()

route_id         string[python]
service_id                Int64
trip_headsign    string[python]
direction_id              int64
shape_id                  Int64
dtype: object

/tmp/ipykernel_198467/4078104989.py:1: UserWarning: Instantiating StringDtype without any arguments.Pass a StringDtype instance to silence this warning.
  trips = pd.read_csv("../data/koda-static/data-tmp/trips.txt", dtype={

,route_id,service_id,trip_headsign,direction_id,shape_id
trip_id,,,,,
14010000631461521,9011001000100000,1,<NA>,1,1014010000482214195
14010000635913522,9011001000100000,2,<NA>,1,1014010000482329256
14010000635914682,9011001000100000,2,<NA>,1,1014010000482329256
14010000635916181,9011001000100000,2,<NA>,1,1014010000482329256
14010000635917621,9011001000100000,2,<NA>,1,1014010000482329256

In [9]:
df = df.join(trips, on="trip_id", how="left", rsuffix="_trip")

df.head()

,id,trip_id,start_date,schedule_relationship,vehicle_id,stop_time_updates,timestamp,route_id,service_id,trip_headsign,direction_id,shape_id
0,14010516247726276,14010000663741929,20240615,0,9031008000500536,"[{'stop_sequence': 25, 'stop_id': '90220010001...",1718438398,9011008001300000,6,<NA>,0.0,6014010000657796244
1,14010516247729020,14010000663747674,20240615,0,9031008000500539,"[{'stop_sequence': 11, 'stop_id': '90220010001...",1718438398,9011008001400000,6,<NA>,1.0,6014010000657802092
2,14010516089523031,14010000656705623,20240615,0,9031001004002220,"[{'stop_sequence': 24, 'stop_id': '90220010050...",1718438398,9011001004000000,6,<NA>,0.0,4014010000492969507
3,14010516113220145,14010000656788822,20240615,0,9031001004302521,"[{'stop_sequence': 21, 'stop_id': '90220010061...",1718438398,9011001004300000,332,<NA>,1.0,4014010000536512790
4,14010516089526040,14010000656705875,20240615,0,9031001004002221,"[{'stop_sequence': 21, 'stop_id': '90220010051...",1718438398,9011001004000000,332,<NA>,1.0,4014010000492969547

In [10]:
routes = pd.read_csv("../data/koda-static/data-tmp/routes.txt", dtype={
  "agency_id": pd.StringDtype,
  "route_short_name": pd.StringDtype,
  "route_long_name": pd.StringDtype,
  "route_desc": pd.StringDtype,
  "route_type": "Int64",
})

routes = routes.set_index("route_id")

print(routes.dtypes)

routes.head()

agency_id           string[python]
route_short_name    string[python]
route_long_name     string[python]
route_type                   Int64
route_desc          string[python]
dtype: object

/tmp/ipykernel_198467/2825749385.py:1: UserWarning: Instantiating StringDtype without any arguments.Pass a StringDtype instance to silence this warning.
  routes = pd.read_csv("../data/koda-static/data-tmp/routes.txt", dtype={
/tmp/ipykernel_198467/2825749385.py:1: UserWarning: Instantiating StringDtype without any arguments.Pass a StringDtype instance to silence this warning.
  routes = pd.read_csv("../data/koda-static/data-tmp/routes.txt", dtype={

,agency_id,route_short_name,route_long_name,route_type,route_desc
route_id,,,,,
9011001000100000,14010000000001001,1,<NA>,700,blåbuss
9011001000200000,14010000000001001,2,<NA>,700,blåbuss
9011001000300000,14010000000001001,3,<NA>,700,blåbuss
9011001000400000,14010000000001001,4,<NA>,700,blåbuss
9011001001000000,14010000000001001,10,Blå linjen,401,tunnelbanans blå linje

In [11]:
df = df.join(routes, on="route_id", how="left", rsuffix="_route")

df.head()

,id,trip_id,start_date,schedule_relationship,vehicle_id,stop_time_updates,timestamp,route_id,service_id,trip_headsign,direction_id,shape_id,agency_id,route_short_name,route_long_name,route_type,route_desc
0,14010516247726276,14010000663741929,20240615,0,9031008000500536,"[{'stop_sequence': 25, 'stop_id': '90220010001...",1718438398,9011008001300000,6,<NA>,0.0,6014010000657796244,14010000000002071,13,<NA>,1000,Waxholmsbolaget
1,14010516247729020,14010000663747674,20240615,0,9031008000500539,"[{'stop_sequence': 11, 'stop_id': '90220010001...",1718438398,9011008001400000,6,<NA>,1.0,6014010000657802092,14010000000002071,14,<NA>,1000,Waxholmsbolaget
2,14010516089523031,14010000656705623,20240615,0,9031001004002220,"[{'stop_sequence': 24, 'stop_id': '90220010050...",1718438398,9011001004000000,6,<NA>,0.0,4014010000492969507,14010000000001001,40,<NA>,100,Pendeltåg
3,14010516113220145,14010000656788822,20240615,0,9031001004302521,"[{'stop_sequence': 21, 'stop_id': '90220010061...",1718438398,9011001004300000,332,<NA>,1.0,4014010000536512790,14010000000001001,43,<NA>,100,Pendeltåg
4,14010516089526040,14010000656705875,20240615,0,9031001004002221,"[{'stop_sequence': 21, 'stop_id': '90220010051...",1718438398,9011001004000000,332,<NA>,1.0,4014010000492969547,14010000000001001,40,<NA>,100,Pendeltåg

In [12]:
from datetime import time

from pandas import Series

stop_times = pd.read_csv("../data/koda-static/data-tmp/stop_times.txt", dtype={
    "trip_id": pd.StringDtype(),
    "stop_id": pd.StringDtype(),
    "stop_headsign": pd.StringDtype(),
})

stop_times = stop_times.set_index(["trip_id", "stop_sequence"])

def time_stamp_to_seconds(time_str: str):
    if time_str == "":
        return pd.NA
    hours, minutes, seconds = map(int, time_str.split(":"))
    total_seconds = hours * 3600 + minutes * 60 + seconds
    return total_seconds

def time_stamp_to_series(date: pd.Timestamp, time_df: pd.Series) -> pd.Series:
    return date + \
        time_df.map(time_stamp_to_seconds).astype("Int64") \
        .map(lambda x: pd.Timedelta(seconds=x) if pd.notna(x) else pd.NA)

myTimestamp = pd.Timestamp(year=year, month=month, day=day)

# 2 hour timezone
timezone_offset = pd.Timedelta(hours=-2)

stop_times["arrival_time"] = time_stamp_to_series(myTimestamp, stop_times["arrival_time"])
stop_times["arrival_time"] = stop_times["arrival_time"] + timezone_offset
stop_times["departure_time"] = time_stamp_to_series(myTimestamp, stop_times["departure_time"])
stop_times["departure_time"] = stop_times["departure_time"] + timezone_offset

print(stop_times.dtypes)

stop_times.head()

arrival_time           datetime64[ns]
departure_time         datetime64[ns]
stop_id                string[python]
stop_headsign          string[python]
pickup_type                     int64
drop_off_type                   int64
shape_dist_traveled           float64
timepoint                       int64
dtype: object

                                       arrival_time      departure_time  \
trip_id           stop_sequence
14010000631461521 1             2024-06-15 05:30:00 2024-06-15 05:30:00
                  2             2024-06-15 05:31:02 2024-06-15 05:31:02
                  3             2024-06-15 05:32:14 2024-06-15 05:32:14
                  4             2024-06-15 05:32:51 2024-06-15 05:32:51
                  5             2024-06-15 05:33:44 2024-06-15 05:33:44

                                          stop_id   stop_headsign  \
trip_id           stop_sequence
14010000631461521 1              9022001010369006  Stora Essingen
                  2              9022001010421001  Stora Essingen
                  3              9022001010645003  Stora Essingen
                  4              9022001010462002  Stora Essingen
                  5              9022001010449001  Stora Essingen

                                 pickup_type  drop_off_type  \
trip_id           stop_sequence
14010000631461521 1                        3              1
                  2                        3              3
                  3                        3              3
                  4                        3              3
                  5                        3              3

                                 shape_dist_traveled  timepoint
trip_id           stop_sequence
14010000631461521 1                             0.00          1
                  2                           430.80          0
                  3                           828.25          0
                  4                          1032.70          0
                  5                          1327.70          0

In [13]:
df = df.join(routes, on="route_id", how="left", rsuffix="_route")

df.head()

,id,trip_id,start_date,schedule_relationship,vehicle_id,stop_time_updates,timestamp,route_id,service_id,trip_headsign,direction_id,shape_id,agency_id,route_short_name,route_long_name,route_type,route_desc,agency_id_route,route_short_name_route,route_long_name_route,route_type_route,route_desc_route
0,14010516247726276,14010000663741929,20240615,0,9031008000500536,"[{'stop_sequence': 25, 'stop_id': '90220010001...",1718438398,9011008001300000,6,<NA>,0.0,6014010000657796244,14010000000002071,13,<NA>,1000,Waxholmsbolaget,14010000000002071,13,<NA>,1000,Waxholmsbolaget
1,14010516247729020,14010000663747674,20240615,0,9031008000500539,"[{'stop_sequence': 11, 'stop_id': '90220010001...",1718438398,9011008001400000,6,<NA>,1.0,6014010000657802092,14010000000002071,14,<NA>,1000,Waxholmsbolaget,14010000000002071,14,<NA>,1000,Waxholmsbolaget
2,14010516089523031,14010000656705623,20240615,0,9031001004002220,"[{'stop_sequence': 24, 'stop_id': '90220010050...",1718438398,9011001004000000,6,<NA>,0.0,4014010000492969507,14010000000001001,40,<NA>,100,Pendeltåg,14010000000001001,40,<NA>,100,Pendeltåg
3,14010516113220145,14010000656788822,20240615,0,9031001004302521,"[{'stop_sequence': 21, 'stop_id': '90220010061...",1718438398,9011001004300000,332,<NA>,1.0,4014010000536512790,14010000000001001,43,<NA>,100,Pendeltåg,14010000000001001,43,<NA>,100,Pendeltåg
4,14010516089526040,14010000656705875,20240615,0,9031001004002221,"[{'stop_sequence': 21, 'stop_id': '90220010051...",1718438398,9011001004000000,332,<NA>,1.0,4014010000492969547,14010000000001001,40,<NA>,100,Pendeltåg,14010000000001001,40,<NA>,100,Pendeltåg

In [14]:
df[(df["route_short_name"] == "40") & (df["route_desc"] == "Pendeltåg")].head()

,id,trip_id,start_date,schedule_relationship,vehicle_id,stop_time_updates,timestamp,route_id,service_id,trip_headsign,direction_id,shape_id,agency_id,route_short_name,route_long_name,route_type,route_desc,agency_id_route,route_short_name_route,route_long_name_route,route_type_route,route_desc_route
2,14010516089523031,14010000656705623,20240615,0,9031001004002220,"[{'stop_sequence': 24, 'stop_id': '90220010050...",1718438398,9011001004000000,6,<NA>,0.0,4014010000492969507,14010000000001001,40,<NA>,100,Pendeltåg,14010000000001001,40,<NA>,100,Pendeltåg
4,14010516089526040,14010000656705875,20240615,0,9031001004002221,"[{'stop_sequence': 21, 'stop_id': '90220010051...",1718438398,9011001004000000,332,<NA>,1.0,4014010000492969547,14010000000001001,40,<NA>,100,Pendeltåg,14010000000001001,40,<NA>,100,Pendeltåg
19,14010516089527825,14010000656705974,20240615,0,9031001004002222,"[{'stop_sequence': 17, 'stop_id': '90220010050...",1718438398,9011001004000000,433,<NA>,0.0,4014010000492969316,14010000000001001,40,<NA>,100,Pendeltåg,14010000000001001,40,<NA>,100,Pendeltåg
25,14010516089529610,14010000656706199,20240615,0,9031001004002223,"[{'stop_sequence': 12, 'stop_id': '90220010053...",1718438398,9011001004000000,332,<NA>,1.0,4014010000492969547,14010000000001001,40,<NA>,100,Pendeltåg,14010000000001001,40,<NA>,100,Pendeltåg
113,14010516089531701,14010000656706391,20240615,0,9031001004002224,"[{'stop_sequence': 8, 'stop_id': '902200100516...",1718438398,9011001004000000,6,<NA>,0.0,4014010000492969507,14010000000001001,40,<NA>,100,Pendeltåg,14010000000001001,40,<NA>,100,Pendeltåg

In [15]:
# Flatten with stop time updates exploded into separate rows
df_exploded = df.explode("stop_time_updates").reset_index(drop=True)

# Extract stop time update details into separate columns
df_exploded["stop_sequence"] = df_exploded["stop_time_updates"].apply(lambda x: x["stop_sequence"])
df_exploded["stop_id"] = df_exploded["stop_time_updates"].apply(lambda x: x["stop_id"])
df_exploded["arrival_time"] = df_exploded["stop_time_updates"].apply(lambda x: x["arrival_time"]).astype("Int64")
df_exploded["arrival_time"] = pd.to_datetime(df_exploded["arrival_time"], unit='s')
df_exploded["departure_time"] = df_exploded["stop_time_updates"].apply(lambda x: x["departure_time"]).astype("Int64")
df_exploded["departure_time"] = pd.to_datetime(df_exploded["departure_time"], unit='s')
df_exploded["stop_time_schedule_relationship"] = df_exploded["stop_time_updates"].apply(lambda x: x["schedule_relationship"])
df_exploded = df_exploded.drop(columns=["stop_time_updates"])

df_exploded["stop_id"] = df_exploded["stop_id"].map(lambda x: pd.NA if x == "" else x).astype(pd.StringDtype())

df_exploded = df_exploded.set_index(["trip_id", "stop_sequence"])

print(df_exploded.dtypes)

df_exploded.head()

id                                          Int64
start_date                                 object
schedule_relationship                       int64
vehicle_id                                  Int64
timestamp                                   int64
route_id                                   object
service_id                                  Int64
trip_headsign                      string[python]
direction_id                              float64
shape_id                                    Int64
agency_id                          string[python]
route_short_name                   string[python]
route_long_name                    string[python]
route_type                                  Int64
route_desc                         string[python]
agency_id_route                    string[python]
route_short_name_route             string[python]
route_long_name_route              string[python]
route_type_route                            Int64
route_desc_route                   string[python]
stop_id                            string[python]
arrival_time                        datetime64[s]
departure_time                      datetime64[s]
stop_time_schedule_relationship             int64
dtype: object

                                                id start_date  \
trip_id           stop_sequence
14010000663741929 25             14010516247726276   20240615
                  26             14010516247726276   20240615
                  27             14010516247726276   20240615
                  28             14010516247726276   20240615
                  29             14010516247726276   20240615

                                 schedule_relationship        vehicle_id  \
trip_id           stop_sequence
14010000663741929 25                                 0  9031008000500536
                  26                                 0  9031008000500536
                  27                                 0  9031008000500536
                  28                                 0  9031008000500536
                  29                                 0  9031008000500536

                                  timestamp          route_id  service_id  \
trip_id           stop_sequence
14010000663741929 25             1718438398  9011008001300000           6
                  26             1718438398  9011008001300000           6
                  27             1718438398  9011008001300000           6
                  28             1718438398  9011008001300000           6
                  29             1718438398  9011008001300000           6

                                trip_headsign  direction_id  \
trip_id           stop_sequence
14010000663741929 25                     <NA>           0.0
                  26                     <NA>           0.0
                  27                     <NA>           0.0
                  28                     <NA>           0.0
                  29                     <NA>           0.0

                                            shape_id          agency_id  \
trip_id           stop_sequence
14010000663741929 25             6014010000657796244  14010000000002071
                  26             6014010000657796244  14010000000002071
                  27             6014010000657796244  14010000000002071
                  28             6014010000657796244  14010000000002071
                  29             6014010000657796244  14010000000002071

                                route_short_name route_long_name  route_type  \
trip_id           stop_sequence
14010000663741929 25                          13            <NA>        1000
                  26                          13            <NA>        1000
                  27                          13            <NA>        1000
                  28                          13            <NA>        1000
                  29                          13            <NA>        1000

                                      route_desc    agency_id_route  \
trip_id           stop_sequence
14010000663741929 25             Waxholmsbolaget  14010000000002071
                  26             Waxholmsbolaget  14010000000002071
                  27             Waxholmsbolaget  14010000000002071
                  28             Waxholmsbolaget  14010000000002071
                  29             Waxholmsbolaget  14010000000002071

                                route_short_name_route route_long_name_route  \
trip_id           stop_sequence
14010000663741929 25                                13                  <NA>
                  26                                13                  <NA>
                  27                                13                  <NA>
                  28                                13                  <NA>
                  29                                13                  <NA>

                                 route_type_route route_desc_route  \
trip_id           stop_sequence
14010000663741929 25                         1000  Waxholmsbolaget
                  26                         1000  Waxholmsbolaget
                  27                         1000  Waxholmsbolaget
                  28                         1000  Waxholmsbolaget
                  29                         1000  Waxholmsbolaget

                                          stop_id        arrival_time  \
trip_id           stop_sequence
14010000663741929 25             9022001000143001 2024-06-15 07:51:16
                  26             9022001000142001 2024-06-15 07:53:16
                  27             9022001000141001 2024-06-15 07:55:06
                  28             9022001000139001 2024-06-15 07:59:29
                  29             9022001000138001 2024-06-15 07:59:59

                                     departure_time  \
trip_id           stop_sequence
14010000663741929 25            2024-06-15 07:52:13
                  26            2024-06-15 07:53:16
                  27            2024-06-15 07:55:49
                  28            2024-06-15 07:59:29
                  29            2024-06-15 08:00:01

                                 stop_time_schedule_relationship
trip_id           stop_sequence
14010000663741929 25                                           0
                  26                                           0
                  27                                           0
                  28                                           0
                  29                                           0

In [16]:
df_exploded_with_stop_times = df_exploded.join(stop_times, on=["trip_id", "stop_sequence"], how="left", rsuffix="_planned")

print(df_exploded_with_stop_times.dtypes)

df_exploded_with_stop_times.head()

id                                          Int64
start_date                                 object
schedule_relationship                       int64
vehicle_id                                  Int64
timestamp                                   int64
route_id                                   object
service_id                                  Int64
trip_headsign                      string[python]
direction_id                              float64
shape_id                                    Int64
agency_id                          string[python]
route_short_name                   string[python]
route_long_name                    string[python]
route_type                                  Int64
route_desc                         string[python]
agency_id_route                    string[python]
route_short_name_route             string[python]
route_long_name_route              string[python]
route_type_route                            Int64
route_desc_route                   string[python]
stop_id                            string[python]
arrival_time                        datetime64[s]
departure_time                      datetime64[s]
stop_time_schedule_relationship             int64
arrival_time_planned               datetime64[ns]
departure_time_planned             datetime64[ns]
stop_id_planned                    string[python]
stop_headsign                      string[python]
pickup_type                               float64
drop_off_type                             float64
shape_dist_traveled                       float64
timepoint                                 float64
dtype: object

                                                id start_date  \
trip_id           stop_sequence
14010000663741929 25             14010516247726276   20240615
                  26             14010516247726276   20240615
                  27             14010516247726276   20240615
                  28             14010516247726276   20240615
                  29             14010516247726276   20240615

                                 schedule_relationship        vehicle_id  \
trip_id           stop_sequence
14010000663741929 25                                 0  9031008000500536
                  26                                 0  9031008000500536
                  27                                 0  9031008000500536
                  28                                 0  9031008000500536
                  29                                 0  9031008000500536

                                  timestamp          route_id  service_id  \
trip_id           stop_sequence
14010000663741929 25             1718438398  9011008001300000           6
                  26             1718438398  9011008001300000           6
                  27             1718438398  9011008001300000           6
                  28             1718438398  9011008001300000           6
                  29             1718438398  9011008001300000           6

                                trip_headsign  direction_id  \
trip_id           stop_sequence
14010000663741929 25                     <NA>           0.0
                  26                     <NA>           0.0
                  27                     <NA>           0.0
                  28                     <NA>           0.0
                  29                     <NA>           0.0

                                            shape_id          agency_id  \
trip_id           stop_sequence
14010000663741929 25             6014010000657796244  14010000000002071
                  26             6014010000657796244  14010000000002071
                  27             6014010000657796244  14010000000002071
                  28             6014010000657796244  14010000000002071
                  29             6014010000657796244  14010000000002071

                                route_short_name route_long_name  route_type  \
trip_id           stop_sequence
14010000663741929 25                          13            <NA>        1000
                  26                          13            <NA>        1000
                  27                          13            <NA>        1000
                  28                          13            <NA>        1000
                  29                          13            <NA>        1000

                                      route_desc    agency_id_route  \
trip_id           stop_sequence
14010000663741929 25             Waxholmsbolaget  14010000000002071
                  26             Waxholmsbolaget  14010000000002071
                  27             Waxholmsbolaget  14010000000002071
                  28             Waxholmsbolaget  14010000000002071
                  29             Waxholmsbolaget  14010000000002071

                                route_short_name_route route_long_name_route  \
trip_id           stop_sequence
14010000663741929 25                                13                  <NA>
                  26                                13                  <NA>
                  27                                13                  <NA>
                  28                                13                  <NA>
                  29                                13                  <NA>

                                 route_type_route route_desc_route  \
trip_id           stop_sequence
14010000663741929 25                         1000  Waxholmsbolaget
                  26                         1000  Waxholmsbolaget
                  27                         1000  Waxholmsbolaget
                  28                         1000  Waxholmsbolaget
                  29                         1000  Waxholmsbolaget

                                          stop_id        arrival_time  \
trip_id           stop_sequence
14010000663741929 25             9022001000143001 2024-06-15 07:51:16
                  26             9022001000142001 2024-06-15 07:53:16
                  27             9022001000141001 2024-06-15 07:55:06
                  28             9022001000139001 2024-06-15 07:59:29
                  29             9022001000138001 2024-06-15 07:59:59

                                     departure_time  \
trip_id           stop_sequence
14010000663741929 25            2024-06-15 07:52:13
                  26            2024-06-15 07:53:16
                  27            2024-06-15 07:55:49
                  28            2024-06-15 07:59:29
                  29            2024-06-15 08:00:01

                                 stop_time_schedule_relationship  \
trip_id           stop_sequence
14010000663741929 25                                           0
                  26                                           0
                  27                                           0
                  28                                           0
                  29                                           0

                                arrival_time_planned departure_time_planned  \
trip_id           stop_sequence
14010000663741929 25             2024-06-15 07:46:00    2024-06-15 07:46:00
                  26             2024-06-15 07:47:00    2024-06-15 07:47:00
                  27             2024-06-15 07:50:00    2024-06-15 07:50:00
                  28             2024-06-15 07:53:00    2024-06-15 07:53:00
                  29             2024-06-15 07:54:00    2024-06-15 07:54:00

                                  stop_id_planned  \
trip_id           stop_sequence
14010000663741929 25             9022001000143001
                  26             9022001000142001
                  27             9022001000141001
                  28             9022001000139001
                  29             9022001000138001

                                                      stop_headsign  \
trip_id           stop_sequence
14010000663741929 25             Strömkajen (Stockholm) via Vaxholm
                  26             Strömkajen (Stockholm) via Vaxholm
                  27             Strömkajen (Stockholm) via Vaxholm
                  28             Strömkajen (Stockholm) via Vaxholm
                  29             Strömkajen (Stockholm) via Vaxholm

                                 pickup_type  drop_off_type  \
trip_id           stop_sequence
14010000663741929 25                     3.0            3.0
                  26                     3.0            3.0
                  27                     3.0            3.0
                  28                     3.0            3.0
                  29                     3.0            3.0

                                 shape_dist_traveled  timepoint
trip_id           stop_sequence
14010000663741929 25                        49495.44        1.0
                  26                        50035.92        1.0
                  27                        50812.21        1.0
                  28                        52063.67        1.0
                  29                        52549.42        1.0

In [23]:
df_exploded_with_stop_times["arrival_time_late"] = (df_exploded_with_stop_times["arrival_time"] - df_exploded_with_stop_times["arrival_time_planned"])
df_exploded_with_stop_times["departure_time_late"] = (df_exploded_with_stop_times["departure_time"] - df_exploded_with_stop_times["departure_time_planned"])

print(df_exploded_with_stop_times[["arrival_time", "arrival_time_planned", "arrival_time_late",
                             "departure_time", "departure_time_planned", "departure_time_late", "agency_id"]].dtypes)

df_exploded_with_stop_times[["arrival_time", "arrival_time_planned", "arrival_time_late",
                             "departure_time", "departure_time_planned", "departure_time_late", "agency_id"]].head()

arrival_time                datetime64[s]
arrival_time_planned       datetime64[ns]
arrival_time_late         timedelta64[ns]
departure_time              datetime64[s]
departure_time_planned     datetime64[ns]
departure_time_late       timedelta64[ns]
agency_id                  string[python]
dtype: object

                                       arrival_time arrival_time_planned  \
trip_id           stop_sequence
14010000663741929 25            2024-06-15 07:51:16  2024-06-15 07:46:00
                  26            2024-06-15 07:53:16  2024-06-15 07:47:00
                  27            2024-06-15 07:55:06  2024-06-15 07:50:00
                  28            2024-06-15 07:59:29  2024-06-15 07:53:00
                  29            2024-06-15 07:59:59  2024-06-15 07:54:00

                                arrival_time_late      departure_time  \
trip_id           stop_sequence
14010000663741929 25              0 days 00:05:16 2024-06-15 07:52:13
                  26              0 days 00:06:16 2024-06-15 07:53:16
                  27              0 days 00:05:06 2024-06-15 07:55:49
                  28              0 days 00:06:29 2024-06-15 07:59:29
                  29              0 days 00:05:59 2024-06-15 08:00:01

                                departure_time_planned departure_time_late  \
trip_id           stop_sequence
14010000663741929 25               2024-06-15 07:46:00     0 days 00:06:13
                  26               2024-06-15 07:47:00     0 days 00:06:16
                  27               2024-06-15 07:50:00     0 days 00:05:49
                  28               2024-06-15 07:53:00     0 days 00:06:29
                  29               2024-06-15 07:54:00     0 days 00:06:01

                                         agency_id
trip_id           stop_sequence
14010000663741929 25             14010000000002071
                  26             14010000000002071
                  27             14010000000002071
                  28             14010000000002071
                  29             14010000000002071

In [18]:
# agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_fare_url
# 14010000000001001,AB Storstockholms Lokaltrafik,https://sl.se/,Europe/Stockholm,sv,https://sl.se/

agencies = pd.read_csv("../data/koda-static/data-tmp/agency.txt", dtype={
  "agency_id": pd.StringDtype(),
  "agency_name": pd.StringDtype(),
  "agency_url": pd.StringDtype(),
  "agency_timezone": pd.StringDtype(),
  "agency_lang": pd.StringDtype(),
  "agency_fare_url": pd.StringDtype(),
})

agencies = agencies.set_index("agency_id")

agencies.head()

,agency_name,agency_url,agency_timezone,agency_lang,agency_fare_url
agency_id,,,,,
14010000000001917,Upplands lokaltrafik,https://www.resrobot.se/,Europe/Stockholm,sv,<NA>
14010000000001983,Kommuner i Stockholms Län,https://www.resrobot.se/,Europe/Stockholm,sv,<NA>
14010000000001939,Länstrafiken Sörmland,https://www.resrobot.se/,Europe/Stockholm,sv,<NA>
14010000000002005,Färdtjänstnämnden,https://www.resrobot.se/,Europe/Stockholm,sv,<NA>
14010000000002071,Waxholmsbolaget Ångfartygs AB,https://www.resrobot.se/,Europe/Stockholm,sv,<NA>

In [28]:
SL_AGENCY_ID = agencies[agencies["agency_name"] == "AB Storstockholms Lokaltrafik"].index[0]
WAXHOLMSBOLAGET_ID = agencies[agencies["agency_name"] == "Waxholmsbolaget Ångfartygs AB"].index[0]

route_dt = df_exploded_with_stop_times[
  (df_exploded_with_stop_times["route_short_name"] == "13") & \
  (df_exploded_with_stop_times["agency_id"] == WAXHOLMSBOLAGET_ID)]
route_dt.head(20)

                                                id start_date  \
trip_id           stop_sequence
14010000663741929 25             14010516247726276   20240615
                  26             14010516247726276   20240615
                  27             14010516247726276   20240615
                  28             14010516247726276   20240615
                  29             14010516247726276   20240615
                  30             14010516247726276   20240615
                  31             14010516247726276   20240615
                  32             14010516247726276   20240615
                  33             14010516247726276   20240615
                  34             14010516247726276   20240615
                  35             14010516247726276   20240615
                  36             14010516247726276   20240615
                  37             14010516247726276   20240615
                  38             14010516247726276   20240615
                  39             14010516247726276   20240615
                  40             14010516247726276   20240615
                  41             14010516247726276   20240615
                  42             14010516247726276   20240615
                  43             14010516247726276   20240615
                  44             14010516247726276   20240615

                                 schedule_relationship        vehicle_id  \
trip_id           stop_sequence
14010000663741929 25                                 0  9031008000500536
                  26                                 0  9031008000500536
                  27                                 0  9031008000500536
                  28                                 0  9031008000500536
                  29                                 0  9031008000500536
                  30                                 0  9031008000500536
                  31                                 0  9031008000500536
                  32                                 0  9031008000500536
                  33                                 0  9031008000500536
                  34                                 0  9031008000500536
                  35                                 0  9031008000500536
                  36                                 0  9031008000500536
                  37                                 0  9031008000500536
                  38                                 0  9031008000500536
                  39                                 0  9031008000500536
                  40                                 0  9031008000500536
                  41                                 0  9031008000500536
                  42                                 0  9031008000500536
                  43                                 0  9031008000500536
                  44                                 0  9031008000500536

                                  timestamp          route_id  service_id  \
trip_id           stop_sequence
14010000663741929 25             1718438398  9011008001300000           6
                  26             1718438398  9011008001300000           6
                  27             1718438398  9011008001300000           6
                  28             1718438398  9011008001300000           6
                  29             1718438398  9011008001300000           6
                  30             1718438398  9011008001300000           6
                  31             1718438398  9011008001300000           6
                  32             1718438398  9011008001300000           6
                  33             1718438398  9011008001300000           6
                  34             1718438398  9011008001300000           6
                  35             1718438398  9011008001300000           6
                  36             1718438398  9011008001300000           6
                  37             1718438398  9011008001300000           6
                  38             1718438398  9011008001300000           6
                  39             1718438398  9011008001300000           6
                  40             1718438398  9011008001300000           6
                  41             1718438398  9011008001300000           6
                  42             1718438398  9011008001300000           6
                  43             1718438398  9011008001300000           6
                  44             1718438398  9011008001300000           6

                                trip_headsign  direction_id  \
trip_id           stop_sequence
14010000663741929 25                     <NA>           0.0
                  26                     <NA>           0.0
                  27                     <NA>           0.0
                  28                     <NA>           0.0
                  29                     <NA>           0.0
                  30                     <NA>           0.0
                  31                     <NA>           0.0
                  32                     <NA>           0.0
                  33                     <NA>           0.0
                  34                     <NA>           0.0
                  35                     <NA>           0.0
                  36                     <NA>           0.0
                  37                     <NA>           0.0
                  38                     <NA>           0.0
                  39                     <NA>           0.0
                  40                     <NA>           0.0
                  41                     <NA>           0.0
                  42                     <NA>           0.0
                  43                     <NA>           0.0
                  44                     <NA>           0.0

                                            shape_id          agency_id  \
trip_id           stop_sequence
14010000663741929 25             6014010000657796244  14010000000002071
                  26             6014010000657796244  14010000000002071
                  27             6014010000657796244  14010000000002071
                  28             6014010000657796244  14010000000002071
                  29             6014010000657796244  14010000000002071
                  30             6014010000657796244  14010000000002071
                  31             6014010000657796244  14010000000002071
                  32             6014010000657796244  14010000000002071
                  33             6014010000657796244  14010000000002071
                  34             6014010000657796244  14010000000002071
                  35             6014010000657796244  14010000000002071
                  36             6014010000657796244  14010000000002071
                  37             6014010000657796244  14010000000002071
                  38             6014010000657796244  14010000000002071
                  39             6014010000657796244  14010000000002071
                  40             6014010000657796244  14010000000002071
                  41             6014010000657796244  14010000000002071
                  42             6014010000657796244  14010000000002071
                  43             6014010000657796244  14010000000002071
                  44             6014010000657796244  14010000000002071

                                route_short_name route_long_name  route_type  \
trip_id           stop_sequence
14010000663741929 25                          13            <NA>        1000
                  26                          13            <NA>        1000
                  27                          13            <NA>        1000
                  28                          13            <NA>        1000
                  29                          13            <NA>        1000
                  30                          13            <NA>        1000
                  31                          13            <NA>        1000
                  32                          13            <NA>        1000
                  33                          13            <NA>        1000
                  34                          13            <NA>        1000
                  35                          13            <NA>        1000
                  36                          13            <NA>        1000
                  37                          13            <NA>        1000
                  38                          13            <NA>        1000
                  39                          13            <NA>        1000
                  40                          13            <NA>        1000
                  41                          13            <NA>        1000
                  42                          13            <NA>        1000
                  43                          13            <NA>        1000
                  44                          13            <NA>        1000

                                      route_desc    agency_id_route  \
trip_id           stop_sequence
14010000663741929 25             Waxholmsbolaget  14010000000002071
                  26             Waxholmsbolaget  14010000000002071
                  27             Waxholmsbolaget  14010000000002071
                  28             Waxholmsbolaget  14010000000002071
                  29             Waxholmsbolaget  14010000000002071
                  30             Waxholmsbolaget  14010000000002071
                  31             Waxholmsbolaget  14010000000002071
                  32             Waxholmsbolaget  14010000000002071
                  33             Waxholmsbolaget  14010000000002071
                  34             Waxholmsbolaget  14010000000002071
                  35             Waxholmsbolaget  14010000000002071
                  36             Waxholmsbolaget  14010000000002071
                  37             Waxholmsbolaget  14010000000002071
                  38             Waxholmsbolaget  14010000000002071
                  39             Waxholmsbolaget  14010000000002071
                  40             Waxholmsbolaget  14010000000002071
                  41             Waxholmsbolaget  14010000000002071
                  42             Waxholmsbolaget  14010000000002071
                  43             Waxholmsbolaget  14010000000002071
                  44             Waxholmsbolaget  14010000000002071

                                route_short_name_route route_long_name_route  \
trip_id           stop_sequence
14010000663741929 25                                13                  <NA>
                  26                                13                  <NA>
                  27                                13                  <NA>
                  28                                13                  <NA>
                  29                                13                  <NA>
                  30                                13                  <NA>
                  31                                13                  <NA>
                  32                                13                  <NA>
                  33                                13                  <NA>
                  34                                13                  <NA>
                  35                                13                  <NA>
                  36                                13                  <NA>
                  37                                13                  <NA>
                  38                                13                  <NA>
                  39                                13                  <NA>
                  40                                13                  <NA>
                  41                                13                  <NA>
                  42                                13                  <NA>
                  43                                13                  <NA>
                  44                                13                  <NA>

                                 route_type_route route_desc_route  \
trip_id           stop_sequence
14010000663741929 25                         1000  Waxholmsbolaget
                  26                         1000  Waxholmsbolaget
                  27                         1000  Waxholmsbolaget
                  28                         1000  Waxholmsbolaget
                  29                         1000  Waxholmsbolaget
                  30                         1000  Waxholmsbolaget
                  31                         1000  Waxholmsbolaget
                  32                         1000  Waxholmsbolaget
                  33                         1000  Waxholmsbolaget
                  34                         1000  Waxholmsbolaget
                  35                         1000  Waxholmsbolaget
                  36                         1000  Waxholmsbolaget
                  37                         1000  Waxholmsbolaget
                  38                         1000  Waxholmsbolaget
                  39                         1000  Waxholmsbolaget
                  40                         1000  Waxholmsbolaget
                  41                         1000  Waxholmsbolaget
                  42                         1000  Waxholmsbolaget
                  43                         1000  Waxholmsbolaget
                  44                         1000  Waxholmsbolaget

                                          stop_id        arrival_time  \
trip_id           stop_sequence
14010000663741929 25             9022001000143001 2024-06-15 07:51:16
                  26             9022001000142001 2024-06-15 07:53:16
                  27             9022001000141001 2024-06-15 07:55:06
                  28             9022001000139001 2024-06-15 07:59:29
                  29             9022001000138001 2024-06-15 07:59:59
                  30             9022001000137001 2024-06-15 08:01:43
                  31             9022001000136001 2024-06-15 08:02:28
                  32             9022001000135001 2024-06-15 08:03:44
                  33             9022001000431001 2024-06-15 08:10:39
                  34             9022001000430001 2024-06-15 08:12:18
                  35             9022001000426001 2024-06-15 08:19:42
                  36             9022001000428001 2024-06-15 08:20:12
                  37             9022001000401006 2024-06-15 08:28:55
                  38             9022001000410001 2024-06-15 08:38:43
                  39             9022001000409001 2024-06-15 08:41:31
                  40             9022001000408001 2024-06-15 08:43:46
                  41             9022001000407001 2024-06-15 08:46:04
                  42             9022001000432001 2024-06-15 08:48:00
                  43             9022001000403001 2024-06-15 08:50:51
                  44             9022001000402001 2024-06-15 08:54:05

                                     departure_time  \
trip_id           stop_sequence
14010000663741929 25            2024-06-15 07:52:13
                  26            2024-06-15 07:53:16
                  27            2024-06-15 07:55:49
                  28            2024-06-15 07:59:29
                  29            2024-06-15 08:00:01
                  30            2024-06-15 08:01:49
                  31            2024-06-15 08:02:28
                  32            2024-06-15 08:03:53
                  33            2024-06-15 08:10:48
                  34            2024-06-15 08:12:32
                  35            2024-06-15 08:19:42
                  36            2024-06-15 08:20:17
                  37            2024-06-15 08:33:27
                  38            2024-06-15 08:39:14
                  39            2024-06-15 08:41:31
                  40            2024-06-15 08:44:42
                  41            2024-06-15 08:46:15
                  42            2024-06-15 08:48:16
                  43            2024-06-15 08:51:35
                  44            2024-06-15 08:54:42

                                 stop_time_schedule_relationship  \
trip_id           stop_sequence
14010000663741929 25                                           0
                  26                                           0
                  27                                           0
                  28                                           0
                  29                                           0
                  30                                           0
                  31                                           0
                  32                                           0
                  33                                           0
                  34                                           0
                  35                                           0
                  36                                           0
                  37                                           0
                  38                                           0
                  39                                           0
                  40                                           0
                  41                                           0
                  42                                           0
                  43                                           0
                  44                                           0

                                arrival_time_planned departure_time_planned  \
trip_id           stop_sequence
14010000663741929 25             2024-06-15 07:46:00    2024-06-15 07:46:00
                  26             2024-06-15 07:47:00    2024-06-15 07:47:00
                  27             2024-06-15 07:50:00    2024-06-15 07:50:00
                  28             2024-06-15 07:53:00    2024-06-15 07:53:00
                  29             2024-06-15 07:54:00    2024-06-15 07:54:00
                  30             2024-06-15 07:56:00    2024-06-15 07:56:00
                  31             2024-06-15 07:57:00    2024-06-15 07:57:00
                  32             2024-06-15 08:00:00    2024-06-15 08:00:00
                  33             2024-06-15 08:05:00    2024-06-15 08:05:00
                  34             2024-06-15 08:06:00    2024-06-15 08:06:00
                  35             2024-06-15 08:15:00    2024-06-15 08:15:00
                  36             2024-06-15 08:17:00    2024-06-15 08:17:00
                  37             2024-06-15 08:25:00    2024-06-15 08:30:00
                  38             2024-06-15 08:35:00    2024-06-15 08:35:00
                  39             2024-06-15 08:36:00    2024-06-15 08:36:00
                  40             2024-06-15 08:40:00    2024-06-15 08:40:00
                  41             2024-06-15 08:41:00    2024-06-15 08:41:00
                  42             2024-06-15 08:42:00    2024-06-15 08:42:00
                  43             2024-06-15 08:45:00    2024-06-15 08:45:00
                  44             2024-06-15 08:47:00    2024-06-15 08:47:00

                                  stop_id_planned  \
trip_id           stop_sequence
14010000663741929 25             9022001000143001
                  26             9022001000142001
                  27             9022001000141001
                  28             9022001000139001
                  29             9022001000138001
                  30             9022001000137001
                  31             9022001000136001
                  32             9022001000135001
                  33             9022001000431001
                  34             9022001000430001
                  35             9022001000426001
                  36             9022001000428001
                  37             9022001000401006

In [20]:
from gtfs import download_gtfs_static_file

GTFS_REGIONAL_STATIC_API_KEY = os.getenv("GTFS_REGIONAL_STATIC_API_KEY")
if not GTFS_REGIONAL_STATIC_API_KEY:
    raise ValueError("GTFS_REGIONAL_STATIC_API_KEY not found in environment variables")

download_gtfs_static_file(Operator.SL, api_key=GTFS_REGIONAL_STATIC_API_KEY, data_dir="../data/gtfs-static")

File ../data/gtfs-static/sl_gtfs_static.zip already exists. Skipping download.

In [21]:
from gtfs import download_gtfs_rt_file

GTFS_REGIONAL_RT_API_KEY = os.getenv("GTFS_REGIONAL_RT_API_KEY")
if not GTFS_REGIONAL_RT_API_KEY:
    raise ValueError("GTFS_REGIONAL_RT_API_KEY not found in environment variables")

download_gtfs_rt_file(Operator.SL, "TripUpdates", api_key=GTFS_REGIONAL_RT_API_KEY, data_dir="../data/gtfs-rt")

File ../data/gtfs-rt/sl_TripUpdates.pb already exists. Skipping download.